### ISSUE TITLE
Log Level, Log output should be allowable as config values.

### ISSUE THREAD

**Issue by alectronic0** [hmcts/nodejs-logging#18]
### What would you like to change?
Log Level, Log output should be allowable as config values

### How do you think that would improve the project?
// Set this config only once
logging.config({ 
    microservice: 'your-service-name', 
    team: 'YOURTEAM',
    environment: 'some-environemnt',
    output: 'single | multi | human',
    json-pretty: true | false,
   loglevel: ALL, TRACE, DEBUG, INFO, WARN, ERROR, FATAL and OFF
});

I will add a bit more code latter maybe put in a pull request and example of how to configure it a bit more soon.

**Comment by alectronic0** [comment]
Just for example of what we've done with our project including how we would use it

app.js
 ````javascript
let express = require('express');
const mainConfig = require('config');

const logging = require('@hmcts/nodejs-logging');
logging.config(mainConfig.get('logging'));
let logger = logging.getLogger('app.js');

//Create Express App
let app = express();
// add logger to express
app.use(logging.express.accessLogger());

````
config/default.yaml
 ````yaml
logging:
  microservice: out_service
  team: our_team
  environment: local
  log-output: single | multi | human
  json-pretty: true | false

````
config/custom-environment-variables.yaml
 ````yaml
logging:
  microservice: REFORM_SERVICE_NAME
  team: REFORM_TEAM
  environment: REFORM_ENVIRONMENT
  log-output: LOG_OUTPUT
  json-pretty: JSON_CONSOLE_PRETTY_PRINT
````
